apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  namespace: {{ .Values.namespace }}
spec:
    containers:
      - name: dev
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["sleep", "infinity"]
        volumeMounts:
          - name: code
            mountPath: {{ .Values.mountPath }}
        env:
          # Set up MLFLOW_TRACKING_URI env variable indicating URI of the Tracking Server to connect to.
          - name: MLFLOW_TRACKING_URI
            value: {{ .Values.mlflowTrackingUri }}
          # Set up SPARK_THRIFT_SERVER_DNS env variable indicating DNS name of the Spark Thrift Server to connect to (to get data
          # from it for training models).
          - name: SPARK_THRIFT_SERVER_DNS
            value: {{ .Values.sparkThriftServerDNS }}
    volumes:
      # PV with code to develop
      - name: code
        persistentVolumeClaim:
          claimName: code-pvc