apiVersion: v1
kind: Service
metadata:
  name: hive-postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: hive-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
