# Job for running a MLflow project.

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mlflow-job.fullname" . }} # Unique name for the Job using the Chart name and Release name
  namespace: {{ .Values.namespace }}
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 2
  template:
    spec:
      # Service Account used for reading a secret for accessing an image from ACR.
      # serviceAccountName: {{ .Values.serviceAccountName }}
      # imagePullSecrets:
      #   - name: {{ .Values.acrSecret }}
      
      volumes:
      # Volume for code pulled by git
      - name: repo
        emptyDir: {}

      {{- if .Values.git.enabled }}
      initContainers:
        - name: git-pull-code
          image: alpine/git
          command:
            - sh
            - -c
            - |
              git clone {{ .Values.git.url }} /repo
              cd /repo
              git checkout -b {{ .Values.git.branch }}
              {{- if .Values.git.commit }}
              git checkout {{ .Values.git.commit }}
              {{- end}}
          volumeMounts:
            - name: repo
              mountPath: /repo
      {{- end }}

      containers:
        - name: mlflow-job
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          # Command to run a MLflow project
          command: ["sh", "-c"]
          args: 
            - {{ .Values.command }}
          env:
          # Set up MLFLOW_TRACKING_URI env variable indicating URI of the Tracking Server to connect to.
          - name: MLFLOW_TRACKING_URI
            value: {{ .Values.mlflowTrackingUri }}
          {{- if .Values.git.enabled }}
          volumeMounts:
            # Mount a volume with MLflow project script pulled from the repo by git-sync
            - name: repo
              mountPath: /mnt/mlproject
              subPath: {{ .Values.git.path }}
          {{- end }}
      restartPolicy: Never