# This ConfigMap prepares a spark-defaults.conf configuration file determining how Spark works. We define here for 
# example to use Iceberg or where the data is stored.

# This config file needs to be saved in the /opt/spark/conf folder, in the Thrift Server pod by mounting this ConfigMap.

# Every value `${VAR_NAME}` will be replaced with the value of the environment variable `VAR_NAME` using envsubst in the init container
# in the deployment. We will set up those env vars in pods where that ConfigMap will be mounted:
# - STORAGE_ACCOUNT - Name of the Storage Account where data warehouse data will be stored
# - SA_ACCESS_KEY - Access key to the Storage Account where data warehouse data will be stored
# - CONTAINER - Name of the container in Storage Account where data warehouse data will be stored

# Create this configmap only if it doesn't exist yet
{{- if not (lookup "v1" "ConfigMap" .Release.Namespace "spark-conf-template") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-conf-template
data:
  spark-defaults.conf.template: |
    # Set the default filesystem. Used when reading / writing data.
    spark.hadoop.fs.defaultFS=abfss://${CONTAINER}@${STORAGE_ACCOUNT}.dfs.core.windows.net/

    # Configs for authentication to Azure Storage Account (to be able to read and save data). STORAGE_ACCOUNT is a name of the Storage Account
    # to use and SA_ACCESS_KEY is an access key to it.
    spark.hadoop.fs.azure.account.key.${STORAGE_ACCOUNT}.dfs.core.windows.net=${SA_ACCESS_KEY}
    
    # Add additional iceberg extensions providing additional functionalities (e.g. merge, time travel)
    spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    


    # Below spark.sql.catalog.iceberg_catalog configs define Iceberg catalog (called "iceberg_catalog", this is a name we can choose here)

    # Define the class used to perform operations on tables from the "iceberg_catalog" catalog
    spark.sql.catalog.iceberg_catalog=org.apache.iceberg.spark.SparkCatalog

    # Define to store metadata of tables from the "iceberg_catalog" catalog in the filesystem (defined by the next iceberg_catalog.warehouse config)
    spark.sql.catalog.iceberg_catalog.type=hadoop

    # Define where to store data of tables from the "iceberg_catalog" catalog
    spark.sql.catalog.iceberg_catalog.warehouse=abfss://${CONTAINER}@${STORAGE_ACCOUNT}.dfs.core.windows.net/{{ .Values.iceberg.catalogFolder }}/




    # Set up the iceberg_catalog as a default catalog. When we create a table without specifying a catalog, this catalog will be used.
    # It is needed for dbt since it creates tables without specifying catalog and it looks like we can't specify the catalog there.
    spark.sql.defaultCatalog=iceberg_catalog
{{- end }}