# This is a PVC used to store code pulled from a repo by git-sync. It uses Azure File Share as data storage. We need an RWX access mode for PV
# so it can be mounted into many pods on different nodes.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
  namespace: airflow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kind-pv-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: azurefile-pv