# This is a PVC used to access DAGs code pulled from a repo by git-sync (which is deployed by the separate 'git_sync' Helm chart). It uses Azure File Share
# as data storage which provides a ReadWriteMany access mode so it can be mounted into many pods on different nodes.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  namespace: airflow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /git_code
  # csi:
  #   driver: file.csi.azure.com  # Driver for Azure File Share
  #   volumeHandle: "{{ .Values.storageAccountName }}#{{ .Values.fileShareName }}""
  #   volumeAttributes:
  #     shareName: {{ .Values.fileShareName }}
  #     storageAccount: {{ .Values.storageAccountName }}
  #   # Secret with the following keys:
  #   #   - azurestorageaccountname - Storage Account name
  #   #   - azurestorageaccountkey - Access key
  #   nodeStageSecretRef:
  #     name: {{ .Values.secretName }}
  #     namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: airflow-dags-pv