# PostgreSQL deployment which will serve as Airflow metadata db

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
        - name: postgres
          image: public.ecr.aws/bitnami/postgresql:16
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgres_database
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /bitnami/postgresql
      volumes:
        - name: pgdata
          emptyDir: {}
