# This is a service account which will be used by Airflow for creating new pods where tasks will be executed (when using KubernetesExecutor or
# KubernetesPodOperator). 
# We specify here a secret which will be used when pulling images in pods created.
# In the role-binding.yaml file, we assing a proper role with permissions to this service account (needed for Airflow to create pods to run tasks in).

apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
  namespace: airflow