# This is a service account which will be used by Airflow for creating new pods where tasks will be executed (when using KubernetesExecutor or
# KubernetesPodOperator). 
# We specify here a secret which will be used when pulling images in pods created.

# We add roles to this SA with permissions for creating pods to run tasks in. 

# There are two roles for two namespaces (so Airflow can create pods in those namespaces):
#   - airflow
#   - spark
#   - mlflow


apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
  namespace: airflow


---
# Role for the 'airflow' namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: airflow
  name: airflow-pod-manager
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - events
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-pod-manager-binding
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-pod-manager
  apiGroup: rbac.authorization.k8s.io

  
# Role for the 'spark' namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark
  name: airflow-pod-manager
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - events
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - patch
  # SparkApplication CRD
  - apiGroups: ["sparkoperator.k8s.io"]
    resources:
      - sparkapplications
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-pod-manager-binding
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-pod-manager
  apiGroup: rbac.authorization.k8s.io

  
# Role for the 'mlflow' namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mlflow
  name: airflow-pod-manager
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - events
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-pod-manager-binding
  namespace: mlflow
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-pod-manager
  apiGroup: rbac.authorization.k8s.io