my_spark_project:
  target: dev
  outputs:
    dev:
      type: spark
      # Use the Thrift protocol for connecting to the remote Spark Thrift Server
      method: thrift
      # DNS name of the Spark Thrift Server (name of the Kubernetes service used for it)
      host: spark-thrift-server
      port: 10000
      user: ""
      # Tables will be saved in the schema called {project_schema}_{profiles_schema}, where:
      #   - project_schema - schema name specified in dbt_project.yml file
      #   - profiles_schema - schema name specified in profiles.yml file
      schema: dwh
      connect_timeout: 30
      retries: 3