# Pod running dbt which connects to the Spark Thrift Server

apiVersion: v1
kind: Pod
metadata:
  name: dbt
  namespace: spark
  labels:
    app: dbt
spec:
  initContainers:
    # Clone code from git repo
    - name: git-init
      image: alpine/git:latest
      command:
        - sh
        - -c
        - |
          git clone --branch {{ .Values.git.branch }} {{ .Values.git.url }} /repo
          cd /repo
          {{- if .Values.git.commit }}
          git checkout {{ .Values.git.commit }}
          {{- end }}
      volumeMounts:
        - name: git-code
          mountPath: /repo

  containers:
    - name: dbt
      image: dbt:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "sleep 3600"]
      # env:
        # - name: SPARK_HOST
        #   value: "spark-thrift-server"
        # - name: SPARK_PORT
        #   value: "10000"
        # - name: SPARK_SCHEMA
        #   value: "default"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      volumeMounts:
        - name: git-repo
          mountPath: /root
          subPath: {{ .Values.git.path }}
          
  volumes:
    - name: git-code
      emptyDir: {}
  restartPolicy: Never
