# ServiceAccount granting Spark permissions to create driver and executor pods, and pull images from ACR.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator
  namespace: {{ .Values.namespace }}
# Get a secret with credentials for authentication to the ACR.
# imagePullSecrets:
#   - name: {{ .Values.acrSecretName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "deletecollection", "patch"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "scheduledsparkapplications"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: spark-operator
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: spark-operator-role
  apiGroup: rbac.authorization.k8s.io