# PostgreSQL deployment which will serve as a metadata db

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            # Env vars for creating a database and user used by Hive
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key: {{ .Values.postgres.secret.userPasswordKey }}
            - name: POSTGRES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key: {{ .Values.postgres.secret.adminPasswordKey }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /bitnami/postgresql
      volumes:
        - name: pgdata
          emptyDir: {}
