# namespace where to create the pod
namespace: mlflow
# Docker image to use
image:
  url: mlflow-spark
  pullPolicy: IfNotPresent
# Path at the host where to store PV's data (when using kind, this is the extraMounts.containerPath parameter from the kind-config.yaml file)
hostPath: /apps
# Path in the pod where we will keep developed code (PV with code will be mounted there)
mountPath: /root/apps
# URI of the MLflow tracking server to use
mlflowTrackingUri: http://tracking-server.mlflow.svc:5000
# DNS name of the Spark Thrift Server to connect to (to get data from it for training models).
sparkThriftServerDNS: spark-thrift-server.spark.svc.cluster.local


# Storage Account and container for storing data warehouse data used by Spark. Those params are used to prepare Spark config files.
storageAccount:
  # Name of the Kubernetes secret with the following keys:
  #   - storage-account - Name of the Storage Account to use
  #   - sa-access-key - Access key to the Storage Account
  secret: adls-sp-secret
  # Name of the Storage Account and container
  name: dwhbulka
  container: dwh

# Name of the folder in Azure Storage Account where is located the Iceberg catalog to use (the same one as the Spark Thrift Server uses)
iceberg:
  catalogFolder: iceberg-warehouse