# This Service Account will be used when we run a MLflow project using the mlflow_project chart for authentication when reading a secret used to pull an image from ACR.
# We will assign to is a proper role in the service-account-role-binding.yaml template.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mlflow.serviceAccountName }}
  namespace: {{ .Values.namespace }}
imagePullSecrets:
- name: {{ .Values.acr.secretName }}
---
# Assign to the Service Account a role allowing for reading secrets (it will read the secret for connecting to ACR)

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{  .Values.mlflow.serviceAccountName }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io