# ServiceAccount granting Spark permissions to create executor pods.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.spark.serviceAccountName }}
  namespace: spark
# Get a secret with credentials for authentication to the ACR.
imagePullSecrets:
  - name: {{ .Values.acrSecret.secretName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-thrift-rolebinding
subjects:
- kind: ServiceAccount
  name: spark-thrift-sa
  namespace: spark
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io