# Service for exposing the Thrift Server.

apiVersion: v1
kind: Service
metadata:
  name: spark-thrift
  namespace: spark
spec:
  selector:
    app: spark-thrift-server
  ports:
  - name: thrift
    port: 10000
    targetPort: 10000
  type: ClusterIP # For external access use `LoadBalancer` or `Ingress`.