# Pod running dbt which connects to the Spark Thrift Server

apiVersion: v1
kind: Pod
metadata:
  name: dbt
  namespace: spark
  labels:
    app: dbt
spec:
  initContainers:
    # Clone code from git repo
    - name: git-init
      image: alpine/git:latest
      command:
        - sh
        - -c
        - |
          git clone --branch {{ params.git.branch }} {{ params.git.url }} /repo
          cd /repo
          {% if params.git.commit %}
          git checkout {{ params.git.commit }}
          {% endif %}
      volumeMounts:
        - name: git-repo
          mountPath: /repo

  containers:
    - name: dbt
      image: "{{ params.image }}"
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          {{ params.dbtCommand }}
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      volumeMounts:
        - name: git-repo
          # Mount to the folder of the user we use in the dbt image
          mountPath: /root
          subPath: "{{ params.git.dbtProjectPath }}"
          
  volumes:
    - name: git-repo
      emptyDir: {}
  restartPolicy: Never
