apiVersion: v2
name: spark-thrift-server
description: Spark Thrift Server with Hive Metastore with PostgreSQL backend
type: application
version: 0.1.0
appVersion: "3.1.3"

# dependencies:
#   # Install PostgreSQL Helm chart which will serve as metadata db for Hive Metastore
#   - name: postgresql
#     version: 15.5.21
#     repository: https://charts.bitnami.com/bitnami