# Run Spark script using Spark Application CRD. We need to have installed Spark Operator to run this.
# We use here a volume with hostPath to provide the Spark script to run.

# Spark configuration:
# We need to provide Spark configuration in the script this Spark Application will run, given by the mainApplicationFile parameter.
# That's because there is a problem with providing dynamic values for those configurations (e.g. from secrets) in the spark-defaults.conf 
# file or here in this YAML manifest.

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: {{ params.resourceName }}
  namespace: {{ params.namespace }}
spec:
  type: Python
  mode: cluster
  pythonVersion: "3"
  imagePullPolicy: {{ params.imagePullPolicy }}
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never

  # Spark script to run. That is a path inside the Spark Driver Pod's container. We need to start this path with 'local:///'
  # if we want to use a local file from the image. Otherwise we need to use the `spark.kubernetes.file.upload.path` Spark configuration
  # to provide information about the location of the script to run.
  mainApplicationFile: "local:///opt/spark/scripts/{{ params.mainApplicationFile }}"

  # Docker image with Spark
  image: {{ params.image }}
  # Get a secret with value for authentication to the ACR.
  # imagePullSecrets:
  # - acr-auth
  
  volumes:
    # Volume with Spark scripts. Use containerPath from kind-config.yaml as the hostPath.path.
    - name: scripts
      hostPath:
        path: /apps   # path on the Kubernetes node with Spark scripts

  # Specify parameters for the Spark Driver Pod
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-operator # Use service account created also in this chart so the driver can create executor pods.
    labels:
      version: 3.3.1

    # Mount a volume with Spark scripts
    volumeMounts:
      - name: scripts
        mountPath: /opt/spark/scripts  # path inside the Spark Driver Pod's container with Spark scripts
    
    env:
      # Set up MLFLOW_TRACKING_URI env variable indicating URI of the Tracking Server to connect to.
      - name: MLFLOW_TRACKING_URI
        value: {{ params.mlflowTrackingUri }}
      # Set up SPARK_THRIFT_SERVER_DNS env variable indicating DNS name of the Spark Thrift Server to connect to (to get data
      # from it for training models).
      - name: SPARK_THRIFT_SERVER_DNS
        value: {{ params.sparkThriftServerDNS }}
      # Env vars related to the Azure Storage Account used for Iceberg catalog. Those values are used to prepare Spark configs
      # in the Python script with Spark app
      - name: STORAGE_ACCOUNT
        valueFrom:
          secretKeyRef:
            name: {{ params.storageAccount.secret }}
            key: storage-account
      - name: SA_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: {{ params.storageAccount.secret }}
            key: sa-access-key
      - name: CONTAINER
        value: {{ params.storageAccount.container }}
      - name: CATALOG_FOLDER
        value: {{ params.icebergCatalogFolder }}


  # Specify parameters for the Spark Executors' Pods 
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.1

    # Mount a volume with Spark scripts
    volumeMounts:
      - name: scripts
        mountPath: /opt/spark/scripts  # path inside the Spark Driver Pod's container with Spark scripts
    
    env:
      # Set up MLFLOW_TRACKING_URI env variable indicating URI of the Tracking Server to connect to.
      - name: MLFLOW_TRACKING_URI
        value: {{ params.mlflowTrackingUri }}
      # Set up SPARK_THRIFT_SERVER_DNS env variable indicating DNS name of the Spark Thrift Server to connect to (to get data
      # from it for training models).
      - name: SPARK_THRIFT_SERVER_DNS
        value: {{ params.sparkThriftServerDNS }}
      # Env vars related to the Azure Storage Account used for Iceberg catalog. Those values are used to prepare Spark configs
      # in the Python script with Spark app
      - name: STORAGE_ACCOUNT
        valueFrom:
          secretKeyRef:
            name: {{ params.storageAccount.secret }}
            key: storage-account
      - name: SA_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: {{ params.storageAccount.secret }}
            key: sa-access-key
      - name: CONTAINER
        value: {{ params.storageAccount.container }}
      - name: CATALOG_FOLDER
        value: {{ params.icebergCatalogFolder }}