apiVersion: v2
name: spark-application
description: Running SparkApplication CRD which uses Spark Operator (Spark Operator needs to be installed separately to run this chart)
type: application
version: 0.1.0
appVersion: "3.1.3"