# Whether or not to create the SparkApplication resource
createSparkApplication: true

# Namespace where to run Spark Operator (where to run Spark driver)
namespace: spark
imagePullPolicy: IfNotPresent
# path of the Spark script to run. This is the path to the Spark script relative to the "apps" folder from this repo (because we mount
# the 'apps' folder from the host into the Spark driver and executor pods in the spark-application.yaml).
mainApplicationFile: test/make_predictions_spark_operator.py
# URL of the Spark image to run
image: mlflow-spark
# URI of the MLflow tracking server to use of the format: http://<mlflow-server-service>.<namespace>.svc:5000, where:
#   - mlflow-server-service - Name of the service that the MLflow tracking server uses
#   - namespace - Namespace where the MLflow tracking server runs
mlflowTrackingUri: http://tracking-server.mlflow.svc:5000
# DNS name of the Spark Thrift Server to connect to (to get data from it for training models) of the format: <spark-service>.<namespace>.svc, where:
#   - spark-service - Name of the service used by the Spark Thrift server
#   - namespace - Namespace where the Spark Thrift server runs
sparkThriftServerDNS: spark-thrift-server.spark.svc.cluster.local


# Storage Account and container for storing data warehouse data used by Spark. Those params are used to prepare Spark config files.
storageAccount:
  # Name of the Kubernetes secret with the following keys:
  #   - storage-account - Name of the Storage Account to use
  #   - sa-access-key - Access key to the Storage Account
  secret: adls-sp-secret
  # Name of the Storage Account and container
  name: dwhbulka
  container: dwh

# Name of the folder in Azure Storage Account where is located the Iceberg catalog to use (the same one as the Spark Thrift Server uses)
iceberg:
  catalogFolder: iceberg-warehouse